---
title: "A Mental Map of the {tidymodels}"
author: Simon Couch
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a working document to help me put my thoughts together on the basics of `parsnip`, `recipes`, `tune`, and `dials`, and how they relate to each other.

### parsnip

The parsnip package supplies a common API for fitting models across many modeling packages.

A "model specification" is made up of a few elementary components:
* type: The type of model being fit---these are the initialization functions in parsnip, and look like `linear_reg()` or `rand_forest()`.
* engine: The package being used to fit the model.
* mode: "classification" or "regression" (set with the `set_mode()` function)

### recipes

Recipes implements a grammar for feature engineering / constructing design matrices.

Initialize a recipe object with `recipe(formula, data)`, where the specification of variables and data are only meant to catalog relevant variables.

`step_*()` functions update the recipe and return it, and include functionality for:
* dummy variables
* encodings
* normalization
* transformations
* filters
* row operations

`all_*()` + `has_role()` functions can be used as select. helpers

Once a recipe object is fully specified, you can estimate coefficients from the training data and recipe with `prep()`, and then apply pre-processing to the training and testing data with `bake()`. 

While building a recipe, tag parameters that need to tuned with `tune("text label")` (formerly `varying()`.)


### tune

tune helps optimize hyperparameters (model parameters that cannot be optimized using the training data itself.)

Again, while building a recipe, tag parameters that need to tuned with `tune("text label")` (formerly `varying()`.) Then, use `dials::parameters()` to detect and collect these flagged parameters.

Use `rsample::vfold_cv()` to carry out `v`-fold cross validation on training data, and then supply it to `tune_grid()` (along with a model, recipe, and grid)

### dials

Supplies default "reasonable" ranges for many parameters, which can be set with `update(text_label = dials::some_function())`, where `text_label` is the label set in `tune("text label")`, as well as `grid_*()` functions to assist with grid searches for optimal hyperparameters.

